### PR TITLE
Update google script.js

### PR DESCRIPTION
**Pull request by udit2303**
Works fine, for some reason some people were having issues with this and added colors

### CODE REVIEW

**Comment by Casper1666** [comment]
i have this same issue when putting the whole webhook in between the quotes, comes with this error - Exception: Request failed for https://discordapp.com returned code 400. Truncated server response: {"embeds": ["0"]} (use muteHttpExceptions option to examine full response). (line 57, file "Code")

**Comment by itszerolove** [comment]
Script is erroring out still. (This is with the latest script.js)

Exception: Request failed for https://discordapp.com returned code 400. Truncated server response: {"embeds": ["0"]} (use muteHttpExceptions option to examine full response) (line 54, file "Code")

**Comment by Casper1666** [comment]
This was solved for me by https://github.com/MrEdinLaw, turns out the form was causing the errors ( mostly) !
Make sure your form has all questions with a "response required" tag ( little slider at each question ), that was causing most of my issues!

**Comment by itszerolove** [comment]
> This was solved for me by https://github.com/MrEdinLaw, turns out the form was causing the errors ( mostly) !
> Make sure your form has all questions with a "response required" tag ( little slider at each question ), that was causing most of my issues!

The form is "response required" for every response :(

**Comment by Casper1666** [comment]
i recommend this - changing the form bit by bit. I had to change the format of mine to work, i wanted a mutiple checkbox in a table format, but it refused to work that way, i had to mix it up a bit and kept trying till i got it to work.
I'm happy to try to help you through it if you want, but i am far from knowing what im doing.
you can discord me on Casper#5167, if you want to try to work it out together. but i had to seek extra help myself.

**Comment by udit2303** [comment]
> > This was solved for me by https://github.com/MrEdinLaw, turns out the form was causing the errors ( mostly)!
> > Make sure your form has all questions with a "response required" tag ( little slider at each question ), that was causing most of my issues!
> 
> The form is "response required" for every response :(

Can I have a link to your form? Seems like your form might be causing this issue because this should be fixed with the new API by discord.

**Comment by Casper1666** [comment]
I had to change to form to make it work...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mariodevx** [comment]
i have the same error, what can i do?

**Comment by Casper1666** [comment]
> 
> 
> i have the same error, what can i do?

Have you made sure every question has a "response required" checked?

**Comment by mariodevx** [comment]
> > i have the same error, what can i do?
> 
> Have you made sure every question has a "response required" checked?

Yes

**Pull request merged**
