### PR TITLE
Code cleanup & updated the code to match ES6

### PR DESCRIPTION
**Pull request by Geekz45679**
**Code cleanup:**
- Fixed indentation
- Changed strings to singlequotes
- Moved some characters to remove lines and reduce clutter

**ES6 Standard update:**
- Changed the old 'var' to the net 'let' and 'const'

**Other stuff:**
- Renamed file to be the proper file format.

### CODE REVIEW

**Comment by dashwav** [comment]
Unfortunately google forms uses Google's [Apps Script](https://en.wikipedia.org/wiki/Google_Apps_Script) which still uses ES5, so these changes will not work on the form script itself.
Out of curiosity did you get this to run at all on your google form? It doesn't even allow me to save this script without popping up an error message.

**Comment by Geekz45679** [comment]
@dashwav That's a shame that Google Apps Script doesn't support ES6, and yes I did get it to work, make sure that the trigger is set up for the onSubmit function.
image

**Here is the code I used to get it to work:** 
```js
var POST_URL = 'URL';

function onSubmit(e) {
	var response = e.response.getItemResponses();
  
	var items = [];
  
	for (var i = 0; i < response.length ; i++) {
		var question = response[i].getItem().getTitle();
		var answer = response[i].getResponse();
	
		if (answer == '') {continue;}
	
		items.push({'name': question, 'value': answer, 'inline': false});
	}
  
	var options = {
		'method' : 'post',
		'payload': JSON.stringify({
	  	'embeds': [{
		  'title': 'TOP TEXT CHANGE THIS IN SCRIPT',
			'fields' :items,
		  'footer': {'text': 'BOTTOM TEXT CHANGE THIS IN SCRIPT'}
			}]
		})
	};
	UrlFetchApp.fetch(POST_URL, options);
}
```

**Comment by dashwav** [comment]
Ah I meant did you get the ES6 compliant code to work, sorry for the misunderstanding.

**Comment by Geekz45679** [comment]
@dashwav No, I don't think Google Scripts likes `let` and it keeps throwing an error.

**Comment by Iku** [comment]
as said it doesnt like ES6, so closed for now, i appreciate you trying tho

**Pull request closed without merging**
